[project]
name = "pyside6-plugin-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "auto-py-to-exe>=2.46.0",
    "pyside6>=6.9.1",
]
